import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '@/components/navbar/Navbar';
import FeaturesFlagProvider from '@/components/FeatureFlag/FeaturesProvider';
import { createFlagsmithInstance } from 'flagsmith/isomorphic';
import './styles/index.scss';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const flagsmith = createFlagsmithInstance();
  await flagsmith.init({
    environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID as string,
  });
  const serverState = flagsmith.getState();
  const allFlags = flagsmith.getAllFlags();
  console.log('serverState:::>>>', serverState);
  console.log('allFlags:::>>>', allFlags);
  console.log('env :::>>>>>', process.env.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID);
  return (
    <html lang='en'>
      <head>
        <link
          href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css'
          rel='stylesheet'
          integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH'
          crossOrigin='anonymous'
        ></link>
      </head>
      <FeaturesFlagProvider serverState={serverState}>
        <body className={inter.className}>
          <Navbar />
          <div className='container'>{children}</div>
          <script
            src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js'
            integrity='sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz'
            crossOrigin='anonymous'
            async
          ></script>
        </body>
      </FeaturesFlagProvider>
    </html>
  );
}
