# This a reusable workflow that will run tests, build app and upload artefact
# We need to create a .env file on the fly to add the env variables required by the next.js app
# to pass the flgsmith env variaviable, we can define it in the env key or mkdir .env as commented below
name: build and run tests
on:
  workflow_call:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install deps
        run: npm ci

      - name: check linting error
        run: npm run lint

      - name: check typescript errors
        run: npm run typeCheck

      - name: run tests
        run: npm run test

      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    env:
      FLAGSMITH_ENVIRONMENT_ID: ${{secrets.FLAGSMITH_ID}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      # - name: create env file
      #   run: |
      #     echo "FLAGSMITH_ENVIRONMENT_ID=${{secrets.FLAGSMITH_ID}}" >> .env

      - name: setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build --production

      - name: upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next/
