name: deploy-and-release
on:
  push:
    branches:
      - main
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  create-version-pr-or-create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        # add fetch-depth and persist-credentials to stop throwing errror when changeset/action try to create a tag in the publish step below.
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: setup node version 20X
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm ci
        # action will create a PR and changelog files if the PR has changesets files.
      - name: create release or PR Version
        id: release
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{secrets.CHANGESETS_TOKEN}}
      - name: print checkout output
        run: echo ' ${{toJson(steps.release.outputs)}}'
