name: CD-and-release
on:
  push:
    branches:
      - main
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  unit-tests-and-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  create-version-pr-or-create-release:
    runs-on: ubuntu-latest
    steps:
      - name: create release or PR Version
        id: release
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{secrets.CHANGESETS_TOKEN}}
