# in this worlflow we use the resuable action build
name: CI
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unit-tests-and-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  list-files:
    runs-on: ubuntu-latest
    needs: unit-tests-and-build
    steps:
      - name: list repo files following use of reusable wf
        run: ls -a

  # echo-success:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: echo workflow
  #       run: echo ${{ github.workflow }}
